# actionlint configuration
# - Declares vars.* names used in workflows so static checking can be strict without false warnings.

config-variables:
  - CI_JWT_SECRET
  - AWS_ROLE_ARN
  - AWS_REGION
  - EVIDENCE_BUCKET
  - EVIDENCE_PREFIX
  - EVIDENCE_HMAC_KEY
  - EVIDENCE_HMAC_KEY_ID
  - ALERT_WEBHOOK_URL
